BASIC_GAIT_PARAMS = [
    "Velocity",
    "Cadence",
    "Cycle Time(sec)/L",
    "Cycle Time(sec)/R",
    "Stride Length(cm)/L",
    "Stride Length(cm)/R",
    "HH Base Support(cm)/L",
    "HH Base Support(cm)/R",
    "Swing % of Cycle/L",
    "Swing % of Cycle/R",
    "Stance % of Cycle/L",
    "Stance % of Cycle/R",
    "Double Supp % Cycle/L",
    "Double Supp % Cycle/R",
    "Toe In / Out/L",
    "Toe In / Out/R",
]

ADVANCED_GAIT_PARAMS = [
    "Velocity",
    "Cadence",
    "Cycle Time(sec)/L",
    "Cycle Time(sec)/R",
    "Stride Length(cm)/L",
    "Stride Length(cm)/R",
    "HH Base Support(cm)/L",
    "HH Base Support(cm)/R",
    "Swing % of Cycle/L",
    "Swing % of Cycle/R",
    "Stance % of Cycle/L",
    "Stance % of Cycle/R",
    "Double Supp % Cycle/L",
    "Double Supp % Cycle/R",
    "Toe In / Out/L",
    "Toe In / Out/R",
    "CV Stride Length/L",
    "CV Stride Length/R",
    "CV Stride Time/L",
    "CV Stride Time/R",
]

